### ISSUE TITLE
error in running upload_files.py

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/micropython-sonoff-webswitch#40]
I succeeded  in compiling yaota8266-build and build-ota-firmware. So I obtained in build folder yaota8266.bin and firmware-ota.bin.
By the way in README.md for the second build you say "make build-firmware" but this doesn't exist; I think it is rather make build-ota-firmware.
First I flashed both yaota8266.bin and firmware-ota.bin then the latest stable micropython firmware.  So far everything is OK and I even tried if Thonny accepted the new installation with success.
I arrive to the bootstrapping with the command "python3 upload_files.py" which fails 
File "upload_files.py" line 5 in <module>
     from utils.main import lint_and_compile
File "/home/me/micropython-sonoff-webswitch/utils/main.py" line 1 in <module>
     from utils.call_flake8 import call_flake8
File "/home/me/micropython-sonoff-webswitch/utils/call_flake8.py" line 4 in <module>
     from flake8.main import cli as flake8cli
ModuleNotFoundError: No module named 'flake8'

Where can we find this 'flake8' ? My folder micropython-sonoff-webswitch have been got normally with git. Is there a PATH problem ?
I indeed would like to achieve a complete result. Thanks in advance for your help and for your patience too.

**Comment by jedie** [comment]
Sorry, the README contains outdated information :(

My preferred way to setup is:

    Generate yaota8266 RSA keys, create config.h and compile yaota8266 and firmware
    Flash yaota8266 and firmware
    format device flash to littlefs2 with: helpers/convert_filesystem.py
    create _config_wifi.json
    Connect device to WiFi
    start soft-OTA to put all missing files to the device

This list is here: https://github.com/jedie/micropython-sonoff-webswitch#quickstart

I will update the readme.

**Comment by jedie** [comment]
I updated the README with: https://github.com/jedie/micropython-sonoff-webswitch/pull/41/commits/d389c1c1feaf206e45d788660a4cbed7a3cb8bd7

Reopen issues if you have problems
