### ISSUE TITLE
Ambiguities between ota-firmware and micropython firmware

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/micropython-sonoff-webswitch#42]
In the previous README we had to flash yaota8266, ota-firmware and classic micropython firmware.
In the new one it is said to only flash yaota8266, ota-firmware. But some lines after we find "Now you have flashed the yaota8266 bootloader and MicroPython Firmware ...".
Do you mean Micropython Firmware is now ota-firmware ?
Assuming yes I am going to proceed  the installation.

**Comment by jedie** [comment]
Yes, sorry for confussion...

"yaota8266" == boot loader and hard-OTA code
"ota-firmware" == "MicroPython Firmware"

The "firmware-combined.bin" is the "normal MicroPython Firmware" not prepared for hard-OTA usage via yaota8266...
