### ISSUE TITLE
I cannot access to REPL

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/micropython-sonoff-webswitch#43]
After normally erasing the esp8266, flashing yaota8266 and ota-firmware, I started thonny via "make thonny", then configured it. The files of micropython-sonoff-webswitch folder are displayed in a left pannel.
In the shell pannel I read: 
 boot8266
HW reset reason : 2
System reset reason : 4
Initial GPIO state : e0030031, OE : 0
Running app
rf_cal[0] !=0x05, is 0xFF
sd ... then exotic characters... on about 2 lines

NB: This information is regularly repeated .

I notice the onboard blue led flashes regularly. My esp8266 is a NodeMCU v0.1 with 4 MB flash.

According the site "https://nodemcu.readthedocs.io/en/master/flash/#tool-overview" ,"rf_cal[0] !=0x05, is 0xFF" would be a symptom that the firmware cannot boot correctly.

By Ctrl-F2 I get "Could not enter REPL"
2 new trials are done with higher timeout. No success and "Giving up".
Then options:
-make sure the device has suitable firmware
-make sure the device is not in bootloader mode
-reset the device and try again (done, this doesn't change the error).
Do you see something wrong with this esp8266 which works very well with Classic Micropython firmware.

**Comment by jedie** [comment]
The only thing I have in the past was wrong flash parameters .
See: https://forum.micropython.org/viewtopic.php?f=16&t=7360#p42174

**Comment by gtcbreizh** [comment]
NodeMcu esp8266 request -fm dio instead dout for flashing. Now I access REPL in thonny IDE. Thanks to have provided a track.
