### ISSUE TITLE
ModuleNotFoundError. No module named 'flake8'

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/micropython-sonoff-webswitch#44]
in make soft-ota the command 'python3 start_soft_ota_server.py' fails:
  File "start_soft_ota_server.py" line 4, in <module>
     from utils.main import lint_and_compile
  File "/home/me/micropython-sonoff-webswitch/utils/main.py" line 2, in <module>
     from utils.call_flake8 import call_flake8
   File "/home/me/micropython-sonoff-webswitch/utils/.call_flake8" line 4, in <module>
      from flake8.main import cli as flake8cli
  ModuleNotFoundError: No module named "flake8".
I did not find myself this "flake8". Is there an error around the name ?

**Comment by jedie** [comment]
> python3 start_soft_ota_server.py

Ah, this is a but. It must be used "pipenv run ..."

**Comment by jedie** [comment]
fix is on the way with https://github.com/jedie/micropython-sonoff-webswitch/pull/45
