### ISSUE TITLE
ota-server and ota-client donot communicate

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/micropython-sonoff-webswitch#46]
I started start_soft_ota_server via "make soft-ota".
A long list of .py files in src folder is compiled to bdist folder.
The other ones in src are copied in bdist folder.

OTA server is started with these info:
Own IP 10.0.2.15       (a question is this IP normal ? Must it be in relation with the local wlan? 
Scan:....:10.0.2.x
Wait for devices on port: 8267 .........................................................indefinitely

On the other size the WiFi connection has been done with Thonny: connected  192.168.1.16 etc...
then ota-client.py is started on Thonny saying:
Wait 15sec for soft-OTA connection on port
2 Reset because: soft-OTA connection on port 8267
1  Reset because: soft-OTA connection on port 8267
then a list of mysterious characters followed by:
boot.py
2 boot.py wait
1 boot.py wait
sys.path=['.','','/lib','/']
On the device uos.list() displays ['boot.py']
and help('modules') a long list of modules (I think it is firmware-ota ?)

Why ota-server and ota-client cannot communicate ? because of IP addresses ?

**Comment by jedie** [comment]
Both parts must be in the same IPv4 sub net. Otherwise the device can't be found.
So 10.0.2.x can not found the device at 192.168.1.16

Maybe the detection of the own IP is wrong. Are you using virtualbox or something?

**Comment by gtcbreizh** [comment]
I use virtualbox. I am going to look for how the local net is seen by virtualbox.

**Comment by gtcbreizh** [comment]
I close because I did not find a solution with Virtualbox

**Comment by jedie** [comment]
I think, you can use bridged networking: https://www.virtualbox.org/manual/ch06.html#network_bridged
Then the linux in the box should be get a IP via your dhcp server and that's in the same sub net.

**Comment by gtcbreizh** [comment]
This networking mode works very well. I could update the application with ota-server, start ota-client, open a webbrowser, display the main/menu page and other linked pages thru the "buttons" in main page. Thanks a lot.
I had tried several networking modes (without success) but not the bridged one which I did not understand well.
