### ISSUE TITLE
make soft-ota error

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/micropython-sonoff-webswitch#47]
After having stopped to work with Virtualbox in Windows10 I installed lubuntu 18.4.3LTS on a partition aside Windows10 (dual boot solution).
All worked up to make soft-ota which starts:
pipenv run start_soft_ota_server.py
Error the command start_soft_ota_server.py could not be found within PATH or Pipfile's [scripts]

This had not appeared in Virtualbox. Why now? Is it a problem with virtualenv ?
I verified start_soft_ota_server.py does exist in micropython-sonoff-webswitch folder.
I added /home/me/micropython-sonoff-webswitch in system PATH. This changes nothing.
How can I add the path in Pipfile to stay in virtualenv?
I add that Thonny does work. For instance for WiFi connexion or to start ota-client.py.

**Comment by jedie** [comment]
Sorry it`s missed in Pipfile
Try this:

pipenv shell
python3 ./start_soft_ota_server.py

**Comment by gtcbreizh** [comment]
This procedure works. Now in lubuntu and a webbrowser I get the various pages of sonoff-webswitch application.
Thanks a lot for your help and congratulations for your very interesting project and work.

**Comment by jedie** [comment]
Now `make soft-ota` should work.

**Comment by gtcbreizh** [comment]
Thanks. I shall try it as soon as possible.

**Comment by gtcbreizh** [comment]
make soft-ota checked successfully ! Congratulations !
